nguage: cpp
compiler:
  - gcc
install:
  - sudo apt-get update
  - sudo apt-get install build-essential gcc-multilib g++-multilib

#  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
# Change this to your needs
script:
  - cd travis-ci/
  - ./travis-ci.sh
